using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace Org.Console.Generators;

/// <summary>
/// Generates:
/// 1. MrAdvice aspect for entry point interception (timing output)
/// 2. Partial Program class with CancellationToken and Stopwatch
/// </summary>
[Generator]
public class EntryPointAdviceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var entryPoint = context.CompilationProvider
            .Select((compilation, ct) => compilation.GetEntryPoint(ct));

        context.RegisterSourceOutput(entryPoint, static (ctx, entryPoint) =>
        {
            if (entryPoint == null)
            {
                return;
            }

            // Build the pointcut pattern for MrAdvice
            // For top-level statements: Program.<Main>$ -> Program.<Main>*
            // For regular Main: Namespace.Program.Main -> Namespace.Program.Main
            var ns = entryPoint.ContainingNamespace.IsGlobalNamespace 
                ? "" 
                : entryPoint.ContainingNamespace.Name + ".";
            var type = entryPoint.ContainingType.Name;
            var method = entryPoint.Name;
            
            // MrAdvice pointcut pattern - only replace $ with * (keep < and > as-is)
            var entryPointPattern = $"{ns}{type}.{method}"
                .TrimStart('.')
                .Replace("$", "*");

            // Check if this is a top-level statement (synthetic <Main>$ method)
            var isTopLevel = method.Contains("<") || method.Contains("$");

            // 1. Generate MrAdvice aspect for timing
            ctx.AddSource("ConsoleSdkTiming.g.cs", SourceText.From($$"""
                // <auto-generated/>
                // Pointcut: {{entryPointPattern}}
                #nullable enable
                #pragma warning disable

                using System;
                using System.Diagnostics;
                using System.Threading.Tasks;
                using ArxOne.MrAdvice.Advice;
                using ArxOne.MrAdvice.Annotation;

                [assembly: Org.ConsoleSdk.Generated.EntryPointTiming]

                namespace Org.ConsoleSdk.Generated
                {
                    [IncludePointcut("{{entryPointPattern}}")]
                    [AttributeUsage(AttributeTargets.Assembly)]
                    internal sealed class EntryPointTimingAttribute : Attribute, IMethodAsyncAdvice
                    {
                        private static bool _hasRun;

                        public async Task Advise(MethodAsyncAdviceContext context)
                        {
                            if (_hasRun)
                            {
                                await context.ProceedAsync();
                                return;
                            }
                            _hasRun = true;

                            Program.Stopwatch.Start();
                            var startTime = DateTime.Now;
                            
                            System.Console.WriteLine($"Started at {startTime:HH:mm:ss.fff}");
                            
                            try
                            {
                                await context.ProceedAsync();
                            }
                            finally
                            {
                                Program.Stopwatch.Stop();
                                System.Console.WriteLine($"Completed in {Program.Stopwatch.ElapsedMilliseconds}ms");
                            }
                        }
                    }
                }
                """, Encoding.UTF8));

            // 2. Generate partial Program with CancellationToken and Stopwatch
            ctx.AddSource("ConsoleSdkRuntime.g.cs", SourceText.From($$"""
                // <auto-generated/>
                #nullable enable
                #pragma warning disable

                using System;
                using System.Diagnostics;
                using System.Threading;

                {{(isTopLevel ? "" : "namespace " + (entryPoint.ContainingNamespace.IsGlobalNamespace ? "global" : entryPoint.ContainingNamespace.ToDisplayString()) + ";")}}

                partial class Program
                {
                    /// <summary>
                    /// CancellationToken that is cancelled when Ctrl+C is pressed.
                    /// </summary>
                    public static CancellationToken CancellationToken => _cts.Token;
                    private static readonly CancellationTokenSource _cts = new();

                    /// <summary>
                    /// Stopwatch for measuring elapsed time.
                    /// </summary>
                    public static Stopwatch Stopwatch { get; } = new();

                    [System.Runtime.CompilerServices.ModuleInitializer]
                    internal static void InitializeConsoleSdk()
                    {
                        System.Console.CancelKeyPress += (_, e) =>
                        {
                            e.Cancel = true;
                            _cts.Cancel();
                        };
                    }
                }
                """, Encoding.UTF8));
        });
    }
}
