#pragma warning disable RS1041
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Operations;
using Microsoft.CodeAnalysis.Text;

namespace Org.Observability.Generators;

/// <summary>
/// Source generator that intercepts Host.Build() and WebApplication.Build() calls
/// to automatically configure OpenTelemetry observability via the Org.Observability runtime library.
/// </summary>
[Generator]
public sealed class ObservabilityInterceptorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all invocation expressions
        var invocations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is InvocationExpressionSyntax,
                transform: TransformInvocation)
            .Where(static x => x is not null)
            .Collect();

        // Register output
        context.RegisterSourceOutput(invocations, GenerateInterceptors);
    }

    private static InterceptionData? TransformInvocation(GeneratorSyntaxContext context, CancellationToken cancellationToken)
    {
        if (context.SemanticModel.GetOperation(context.Node, cancellationToken) is not IInvocationOperation invocation)
            return null;

        var methodName = invocation.TargetMethod.Name;
        var containingType = invocation.TargetMethod.ContainingType;
        
        // Check for Host builder pattern: IHostBuilder.Build() or IHostApplicationBuilder.Build()
        if (methodName == "Build")
        {
            var typeFullName = containingType.ToDisplayString();
            
            // Get the location of the .Build() method name for interception
            var invocationSyntax = (InvocationExpressionSyntax)context.Node;
            var methodNameLocation = GetMethodNameLocation(invocationSyntax);
            
            // WebApplicationBuilder.Build()
            if (typeFullName == "Microsoft.AspNetCore.Builder.WebApplicationBuilder")
            {
                return new InterceptionData(
                    InterceptionKind.WebApplicationBuilder,
                    context.Node.SyntaxTree.FilePath,
                    methodNameLocation.line,
                    methodNameLocation.character
                );
            }
            
            // HostApplicationBuilder.Build()
            if (typeFullName == "Microsoft.Extensions.Hosting.HostApplicationBuilder")
            {
                return new InterceptionData(
                    InterceptionKind.HostApplicationBuilder,
                    context.Node.SyntaxTree.FilePath,
                    methodNameLocation.line,
                    methodNameLocation.character
                );
            }
            
            // IHostBuilder.Build()
            if (containingType.AllInterfaces.Any(i => i.ToDisplayString() == "Microsoft.Extensions.Hosting.IHostBuilder") ||
                typeFullName == "Microsoft.Extensions.Hosting.IHostBuilder")
            {
                return new InterceptionData(
                    InterceptionKind.HostBuilder,
                    context.Node.SyntaxTree.FilePath,
                    methodNameLocation.line,
                    methodNameLocation.character
                );
            }
        }

        return null;
    }

    private static (int line, int character) GetMethodNameLocation(InvocationExpressionSyntax invocation)
    {
        // For member access like "builder.Build()", get the location of "Build"
        if (invocation.Expression is MemberAccessExpressionSyntax memberAccess)
        {
            var nameSpan = memberAccess.Name.GetLocation().GetLineSpan();
            return (nameSpan.StartLinePosition.Line + 1, nameSpan.StartLinePosition.Character + 1);
        }
        
        // Fallback to the invocation start
        var span = invocation.GetLocation().GetLineSpan();
        return (span.StartLinePosition.Line + 1, span.StartLinePosition.Character + 1);
    }

    private static void GenerateInterceptors(SourceProductionContext context, ImmutableArray<InterceptionData?> interceptions)
    {
        var validInterceptions = interceptions
            .Where(i => i is not null)
            .OrderBy(i => i!.FilePath + ":" + i.Line.ToString("D6") + ":" + i.Character.ToString("D6"))
            .ToList();

        if (validInterceptions.Count == 0)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine();
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.Hosting;");
        sb.AppendLine("using Org.Observability;");
        sb.AppendLine();
        
        // Include the InterceptsLocationAttribute in this file since file-scoped types can't cross files
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        sb.AppendLine("    file sealed class InterceptsLocationAttribute : global::System.Attribute");
        sb.AppendLine("    {");
        sb.AppendLine("        public InterceptsLocationAttribute(string filePath, int line, int character) { }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        
        sb.AppendLine("namespace Org.Observability.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    file static class Interceptors");
        sb.AppendLine("    {");
        
        // Determine console exporter setting via preprocessor - this will be evaluated at compile time
        // in the consuming project where ORG_OBSERVABILITY_CONSOLE_EXPORTER may be defined
        sb.AppendLine("#if ORG_OBSERVABILITY_CONSOLE_EXPORTER");
        sb.AppendLine("        private const bool EnableConsoleExporter = true;");
        sb.AppendLine("#else");
        sb.AppendLine("        private const bool EnableConsoleExporter = false;");
        sb.AppendLine("#endif");
        sb.AppendLine();

        var index = 0;
        foreach (var interception in validInterceptions)
        {
            if (interception is null)
                continue;

            switch (interception.Kind)
            {
                case InterceptionKind.WebApplicationBuilder:
                    sb.AppendLine($$"""
                        // Intercepted: WebApplicationBuilder.Build() at {{interception.FilePath}}:{{interception.Line}}:{{interception.Character}}
                        [InterceptsLocation(@"{{interception.FilePath}}", {{interception.Line}}, {{interception.Character}})]
                        public static global::Microsoft.AspNetCore.Builder.WebApplication Intercept_Build_{{index}}(this global::Microsoft.AspNetCore.Builder.WebApplicationBuilder builder)
                        {
                            global::Org.Observability.OrgObservabilityExtensions.ConfigureOrgObservability(builder.Services, builder.Configuration, EnableConsoleExporter);
                            global::Org.Observability.OrgObservabilityExtensions.ConfigureOrgObservabilityLogging(builder.Logging, EnableConsoleExporter);
                            return builder.Build();
                        }
""");
                    break;

                case InterceptionKind.HostApplicationBuilder:
                    sb.AppendLine($$"""
                        // Intercepted: HostApplicationBuilder.Build() at {{interception.FilePath}}:{{interception.Line}}:{{interception.Character}}
                        [InterceptsLocation(@"{{interception.FilePath}}", {{interception.Line}}, {{interception.Character}})]
                        public static global::Microsoft.Extensions.Hosting.IHost Intercept_Build_{{index}}(this global::Microsoft.Extensions.Hosting.HostApplicationBuilder builder)
                        {
                            global::Org.Observability.OrgObservabilityExtensions.ConfigureOrgObservability(builder.Services, builder.Configuration, EnableConsoleExporter);
                            global::Org.Observability.OrgObservabilityExtensions.ConfigureOrgObservabilityLogging(builder.Logging, EnableConsoleExporter);
                            return builder.Build();
                        }
""");
                    break;

                case InterceptionKind.HostBuilder:
                    sb.AppendLine($$"""
                        // Intercepted: IHostBuilder.Build() at {{interception.FilePath}}:{{interception.Line}}:{{interception.Character}}
                        [InterceptsLocation(@"{{interception.FilePath}}", {{interception.Line}}, {{interception.Character}})]
                        public static global::Microsoft.Extensions.Hosting.IHost Intercept_Build_{{index}}(this global::Microsoft.Extensions.Hosting.IHostBuilder builder)
                        {
                            builder.ConfigureServices((context, services) => global::Org.Observability.OrgObservabilityExtensions.ConfigureOrgObservability(services, context.Configuration, EnableConsoleExporter));
                            builder.ConfigureLogging(logging => global::Org.Observability.OrgObservabilityExtensions.ConfigureOrgObservabilityLogging(logging, EnableConsoleExporter));
                            return builder.Build();
                        }
""");
                    break;
            }

            index++;
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("ObservabilityInterceptors.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}

internal enum InterceptionKind
{
    WebApplicationBuilder,
    HostApplicationBuilder,
    HostBuilder
}

internal sealed class InterceptionData
{
    public InterceptionData(InterceptionKind kind, string filePath, int line, int character)
    {
        Kind = kind;
        FilePath = filePath;
        Line = line;
        Character = character;
    }
    
    public InterceptionKind Kind { get; }
    public string FilePath { get; }
    public int Line { get; }
    public int Character { get; }
}
